// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucmufkjogrxfgmjdipxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbXVma2pvZ3J4ZmdtamRpcHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzE0ODEsImV4cCI6MjA3Mjc0NzQ4MX0.0KFEZjn6gK3DRJFX1WjmOmIv7Jv4f94IyQBOEkChvG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});